### ISSUE TITLE
Cache conversations

### ISSUE THREAD

**Issue by rhn** [danigm/fractal#3]
When clicking on a room - even the currently open one - the conversation list reloads from scratch. The delay can be long, and in case of no internet access, looking at different rooms becomes impossible.

**Comment by danigm** [comment]
Yes, this is because we're always doing a initial sync with matrix server and then render the messages from that sync. The first sync is slow sometimes so to show information before the first sync we're showing previous messages.

We need to find a way to avoid the reload and only add new messages... or if it's not possible we should wait for the first sync.

**Comment by danigm** [comment]
And this is also related with message rendering. Messages are cached in memory, but takes time to render, so to avoid to lock the interface we launch a timeout to render each message in the background and when all messages are rendered the loading is hidden.

**Comment by danigm** [comment]
This is fixed now, messages should render quickly with the last commit
